---
title: How the US Army uses data to improve the lives of soldiers
author:  Anuruddha Ananda 
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_notebook:
    toc: yes
    toc_depth: 2
---

<iframe width="560" height="315" src="https://www.youtube.com/embed/3WC4ot8z584" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external ="1"></iframe>


## Why was data driven decision making (3DM) useful in this business case?

Major Paul Lester, Director of Research for the Office of the Deputy Under Secretary of the Army and his team has built an enormous database for securely and anonymously analyzing and experimenting with that data to improve life of soldiers. (Lester, 2013)

## How did the organization apply 3DM?

They have run analyses on over 16,000 soldiers entering basic training to measure psychological health and resilience throughout the training. Get clear picture where each and every soldier stand. (Psychol,2013)

## What can the organization do with 3DM that they couldn’t do before?

army has data of soldiers and their family members also. select the right person to train can reduce PTSD. reduce healthcare utilization and military healthcare budget (Psychol,2013)

## references

re:Work with Google (2014, November 10). How the US Army uses data to improve the lives of soldiers [Video]. YouTube. https://www.youtube.com/watch?v=3WC4ot8z584

RE:WORK EDITORS NOVEMBER 24, 2015 How the US Army uses data to improve the lives of soldiers Retrieved on 2 October 2021 from https://www.frontiersin.org/articles/10.3389/fpsyg.2013.00934/full?utm_source=newsletter&utm_medium=web&utm_campaign=Psychology-w6-2014

TECHNOLOGY REPORT article December 13, 2013 The Person-Event Data Environment: leveraging big data for studies of psychological strengths in soldiers Retrieved on 2 October 2021 from https://rework.withgoogle.com/blog/how-the-army-uses-data-to-improve-soldiers-lives/
